### ISSUE TITLE
Rivington: Custom colour schemes are not applied in the editor

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#2169]
I hope I'm not missing anything obvious. In my several test sites with Rivington, the custom colour schemes are applied correctly on the front of the site, but the editor remains the default.

As an example, this is what I see on the front-end:
<img width="1411" alt="Screenshot 2020-06-23 at 12 20 04" src="https://user-images.githubusercontent.com/908665/85398281-e73e8e80-b54c-11ea-9afd-2f4e8123e169.png">

But the page appears like this in the editor:
<img width="1410" alt="Screenshot 2020-06-23 at 12 28 05" src="https://user-images.githubusercontent.com/908665/85398398-135a0f80-b54d-11ea-8cbe-67a0a15ac204.png">

I've also seen some weirdness in Gutenberg UI. The custom colours might be bleeding to the UI.
<img width="282" alt="Screenshot 2020-06-23 at 12 29 13" src="https://user-images.githubusercontent.com/908665/85398705-8d8a9400-b54d-11ea-9e8c-8518b82f624a.png">

Tested with Mac Chrome, Simple site on the premium plan.

cc @kjellr @ianstewart @alaczek

**Comment by kjellr** [comment]
That's super weird. I can reproduce, but only when using this color scheme: 

<img width="279" alt="Screen Shot 2020-06-23 at 7 49 55 AM" src="https://user-images.githubusercontent.com/1202812/85400287-2efdef80-b526-11ea-991e-da99a7fbf0b6.png">

@iamtakashi can you test the other two and see if they show up in the editor?

**Comment by iamtakashi** [comment]
Thanks for looking into this so quickly, @kjellr!

The issue is happening to me with all the pre-defined palettes and a totally custom one.

![Screenshot 2020-06-23 at 13 02 02](https://user-images.githubusercontent.com/908665/85401641-418e1e00-b552-11ea-817b-ee36586089df.png)

**Comment by kjellr** [comment]
Hmm. Ok, that's odd. Are Coutoire and Alves working fine for you?

In any case, @allancole can take a look as soon as he gets on. 👍

**Comment by iamtakashi** [comment]
> Are Coutoire and Alves working fine for you?

Not for me. Both themes share the same issues including the bleeding to the UI. A colour scheme gets applied on the front of the site, but the editor.

**Comment by kjellr** [comment]
Ok got it. That sounds like it may be an issue with editor styles in the Color Annotations plugin then. We'll dig into it. 👍

**Comment by iamtakashi** [comment]
Ok, thank you 🙇🏻‍♂️

Not sure what happened, but now I see the colour scheme applied to the editor, but the front of the site. The exact opposite of what I initially experienced... Emptying cache and hard reloading didn't help.

![Screenshot 2020-06-23 at 13 48 26](https://user-images.githubusercontent.com/908665/85405797-d3992500-b558-11ea-98db-a853f9364292.png)

**Comment by kjellr** [comment]
🤔 That's _very_ weird!

**Comment by allancole** [comment]
I’m having trouble replicating this. Tried with both a Free and a Premium plan and everything works as expected for me. Are there any other steps I need to do to replicate? 

Also, this might be a silly question, but have you run `svn up` on the `/home` directory to make sure the latest version of the colors.php plugin is in sync?

**Comment by kjellr** [comment]
@allancole I was able to reproduce part of this on my non-sandboxed test site. I'll DM you the details so you can take a look too.

**Comment by allancole** [comment]
So I’m able to replicate the issue now and I figured out what’s happening here but I haven’t figured out _why_ it’s happening. On the front-end, the **editor** annotation file (`wpcom-editor-colors.php`) is being loaded instead of the frontend annotation file (`wpcom-colors.php`). 

![image](https://user-images.githubusercontent.com/709581/85427247-82ce0000-b549-11ea-9c15-404bc3c71d57.png)

It’s unclear, why it’s doing this now especially since just a few moments ago, it loaded the correct annotation. I’ll do some digging…

**Comment by mendezcode** [comment]
@allancole and myself are debugging this issue.

So far we have confirmed that the issue happens only on live sites.
When you sandbox the same site, it works as expected.

We are currently investigating what is going on.
Will keep you all posted.

**Comment by jeffikus** [comment]
I'm looking into this today.

**Comment by jeffikus** [comment]
Ok, so this is possibly a multi layered issue. @allancole and I walked through this today on a live site and in sandbox. I dug into the color annotations code as well, and we've narrowed it down to this:

On the [live site](https://jeffikus831307813.wordpress.com) (premium plan with Rivington):
- Customizer palette choice: https://cloudup.com/cOwbVrJL9sD
- Frontend: https://cloudup.com/c5_nQCdJ_WF 
- The editor: https://cloudup.com/cQV1NUksAGY
There are 3 different styles being applied. Where some of those colors come from I have no idea. One concerning thing is the "dim" style that is overriding the editor color https://cloudup.com/coCBYT1mQlr

On the sandbox of the same site:
- Customizer palette choice: https://cloudup.com/cihZSIrdzqj
- Frontend : https://cloudup.com/c9T-vZhQfBG
- The editor: https://cloudup.com/cO3UV1mjQIV
So, the editor looks to be displaying the color palette correctly, but the customizer and frontend are pulling in an overriding style.

@allancole then discovered that the primary color and other color choices are actually outputting different styles in the editor. 
- Primary blue: https://cloudup.com/ctq_BjDrPeH
- Secondary yellow: https://cloudup.com/cko9yqohbIn
This leads us to believe whatever the primary color is, functions differently to the other color choices. That means it's likely an annotation issue and not the cache.

We tested this on the other palettes to make sure:
- Primary: https://cloudup.com/ccQN-CfaRTM
- Secondary: https://cloudup.com/c8flOZaAK7P

@allancole suggested **we regenerate the annotations from scratch as a first point to fix this.** I haven't done this before, so I'll need assistance on this tomorrow please.

If this is a multilayered problem (let's hope not) and the regeneration of the annotations doesn't fix the issue, we can dig further into the plugin code.

**Comment by kjellr** [comment]
> we regenerate the annotations from scratch as a first point to fix this. I haven't done this before, so I'll need assistance on this tomorrow please.

This seems like a super-painful way to deal with this, and based on what I'm seeing above I'm not sure it's necessary. When I switch from the customizer to the live site, I'm seeing _totally_ different color options. It seems unlikely to me that would be caused by a bug in the individual color annotations — especially if they otherwise work well when sandboxed (see my next comment). 

> On the sandbox of the same site:
> 
> - Customizer palette choice: https://cloudup.com/cihZSIrdzqj
> - Frontend : https://cloudup.com/c9T-vZhQfBG
> - The editor: https://cloudup.com/cO3UV1mjQIV
> So, the editor looks to be displaying the color palette correctly, but the customizer and frontend are pulling in an overriding style.

This is just a tiny bug 😄 — I missed this when I was adjusting some of these styles a few weeks back. These two lines... 

https://github.com/Automattic/themes/blob/f831c060fc1969bca7310649c5550b22d90c13ee/rivington/inc/wpcom-colors.php#L267-L268

... need to be changed to ...

```
array( '.wp-block-cover.has-background-dim:not([class*="background-color"]),
		.wp-block-cover-image.has-background-dim:not([class*="background-color"]),
``` 

... and that should fix it. 

> @allancole then discovered that the primary color and other color choices are actually outputting different styles in the editor.

The styles you're highlighting there are inline ones. Those are [generated from here](https://github.com/Automattic/themes/blob/master/alves/functions.php#L56-L107), and added directly by Gutenberg. If those are part of the problem, then I'd take a look at the functions there and make sure they're working correctly.

**Comment by jeffikus** [comment]
@kjellr thanks for that, nice find! I have tested that and it solves the majority of the above. I spent some time thinking about the add_theme_support('editor-color-palette') section. It is possible that that is getting cached. I'm going to submit a PR tomorrow for Rivington for the above and see if a cacheless version of Rivington works.

**Comment by jeffikus** [comment]
I resolved this on the live site - it turns out it was additional cache that was being applied in the colors plugin. If it isn't resolved for anyone, please let me know and I'll explain how to solve it in the backend.

**Comment by iamtakashi** [comment]
> If it isn't resolved for anyone, please let me know and I'll explain how to solve it in the backend.

Do existing sites need to re-save their custom colours?
